#!/bin/bash

###############################################################################
# GoldenMunch POS Kiosk Autostart Setup Script
# For Raspberry Pi OS (Debian 13/Trixie) with Wayland/Labwc
###############################################################################

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get current user and home directory
CURRENT_USER=$(whoami)
HOME_DIR=$(eval echo ~$CURRENT_USER)
PROJECT_DIR="$HOME_DIR/GoldenMunch_POS-System-With-Custom-Cake-Editor"

echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   GoldenMunch POS Kiosk Autostart Setup Script       ║${NC}"
echo -e "${BLUE}║   For Raspberry Pi with Wayland/Labwc                 ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
echo ""

# Function to print status messages
print_status() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

print_info() {
    echo -e "${BLUE}[i]${NC} $1"
}

# Check if running as root
if [ "$EUID" -eq 0 ]; then
    print_error "Please do not run this script as root or with sudo"
    print_info "Run: ./setup-kiosk-autostart.sh"
    exit 1
fi

print_info "Current user: $CURRENT_USER"
print_info "Home directory: $HOME_DIR"
print_info "Project directory: $PROJECT_DIR"
echo ""

# Verify project directory exists
if [ ! -d "$PROJECT_DIR" ]; then
    print_error "Project directory not found: $PROJECT_DIR"
    print_info "Please update the PROJECT_DIR variable in this script"
    exit 1
fi

print_status "Project directory found"

# Step 1: Install required packages
echo -e "\n${BLUE}Step 1: Installing required packages...${NC}"
print_info "This will install: chromium-browser, wlopm, unclutter"

# Update package list
sudo apt-get update -qq

# Install packages
PACKAGES="chromium-browser wlopm unclutter"
for package in $PACKAGES; do
    if dpkg -l | grep -q "^ii  $package "; then
        print_status "$package is already installed"
    else
        print_info "Installing $package..."
        sudo apt-get install -y $package
        print_status "$package installed"
    fi
done

# Step 2: Create the main kiosk startup script
echo -e "\n${BLUE}Step 2: Creating kiosk startup script...${NC}"

cat > "$HOME_DIR/start-kiosk.sh" << 'EOFSCRIPT'
#!/bin/bash

# GoldenMunch Kiosk Startup Script for Wayland
# Auto-generated by setup-kiosk-autostart.sh

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="$SCRIPT_DIR/GoldenMunch_POS-System-With-Custom-Cake-Editor"
LOG_FILE="$HOME/kiosk-startup.log"

# Redirect output to log file
exec 1>>"$LOG_FILE" 2>&1

echo "=========================================="
echo "GoldenMunch Kiosk Starting: $(date)"
echo "=========================================="

# Wait for system to be ready
echo "Waiting for system initialization..."
sleep 10

# Set environment variables for Wayland
export XDG_SESSION_TYPE=wayland
export XDG_RUNTIME_DIR=/run/user/$(id -u)

# Disable screen blanking
if command -v wlopm &> /dev/null; then
    echo "Disabling screen blanking..."
    wlopm --on '*' &
fi

# Start the backend server
echo "Starting backend server..."
cd "$PROJECT_DIR/server"
if [ -f "package.json" ]; then
    # Kill any existing node processes
    pkill -f "node.*server" || true

    # Start the server
    npm start > "$HOME/server-output.log" 2>&1 &
    SERVER_PID=$!
    echo "Backend server started with PID: $SERVER_PID"
else
    echo "ERROR: Server package.json not found!"
fi

# Wait for backend to start
echo "Waiting for backend to initialize..."
sleep 8

# Start the kiosk frontend
echo "Starting kiosk frontend..."
cd "$PROJECT_DIR/client/Kiosk_Web"
if [ -f "package.json" ]; then
    # Kill any existing frontend processes
    pkill -f "next-server.*3000" || true

    # Start the frontend
    npm run dev > "$HOME/frontend-output.log" 2>&1 &
    FRONTEND_PID=$!
    echo "Frontend started with PID: $FRONTEND_PID"
else
    echo "ERROR: Frontend package.json not found!"
fi

# Wait for frontend to start
echo "Waiting for frontend to initialize..."
sleep 12

# Wait for the frontend to be accessible
echo "Checking if frontend is ready..."
MAX_RETRIES=30
RETRY_COUNT=0
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if curl -s http://localhost:3000 > /dev/null 2>&1; then
        echo "Frontend is ready!"
        break
    fi
    echo "Waiting for frontend... ($((RETRY_COUNT + 1))/$MAX_RETRIES)"
    sleep 2
    RETRY_COUNT=$((RETRY_COUNT + 1))
done

if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    echo "WARNING: Frontend did not respond after $MAX_RETRIES attempts"
fi

# Hide cursor
if command -v unclutter &> /dev/null; then
    echo "Hiding cursor..."
    unclutter -idle 1 -root &
fi

# Launch Chromium in kiosk mode for Wayland
echo "Launching Chromium browser in kiosk mode..."
chromium-browser \
  --kiosk \
  --noerrdialogs \
  --disable-infobars \
  --no-first-run \
  --disable-session-crashed-bubble \
  --disable-restore-session-state \
  --check-for-update-interval=31536000 \
  --start-fullscreen \
  --disable-pinch \
  --overscroll-history-navigation=0 \
  --ozone-platform=wayland \
  --enable-features=UseOzonePlatform \
  --app=http://localhost:3000 \
  > "$HOME/chromium-output.log" 2>&1 &

CHROMIUM_PID=$!
echo "Chromium started with PID: $CHROMIUM_PID"

echo "=========================================="
echo "GoldenMunch Kiosk startup complete!"
echo "Backend PID: $SERVER_PID"
echo "Frontend PID: $FRONTEND_PID"
echo "Chromium PID: $CHROMIUM_PID"
echo "=========================================="

# Keep script running
wait
EOFSCRIPT

chmod +x "$HOME_DIR/start-kiosk.sh"
print_status "Kiosk startup script created: $HOME_DIR/start-kiosk.sh"

# Step 3: Create Labwc autostart configuration
echo -e "\n${BLUE}Step 3: Configuring Labwc autostart...${NC}"

mkdir -p "$HOME_DIR/.config/labwc"

cat > "$HOME_DIR/.config/labwc/autostart" << EOFAUTO
# GoldenMunch Kiosk Autostart for Labwc
# Auto-generated by setup-kiosk-autostart.sh

# Disable screen blanking
wlopm --on '*' &

# Start the kiosk
$HOME_DIR/start-kiosk.sh &
EOFAUTO

chmod +x "$HOME_DIR/.config/labwc/autostart"
print_status "Labwc autostart configured: $HOME_DIR/.config/labwc/autostart"

# Step 4: Create systemd user service (alternative method)
echo -e "\n${BLUE}Step 4: Creating systemd user service...${NC}"

mkdir -p "$HOME_DIR/.config/systemd/user"

cat > "$HOME_DIR/.config/systemd/user/goldenmunch-kiosk.service" << EOFSERVICE
[Unit]
Description=GoldenMunch Kiosk
After=graphical-session.target

[Service]
Type=simple
Environment="DISPLAY=:0"
Environment="XDG_SESSION_TYPE=wayland"
Environment="XDG_RUNTIME_DIR=/run/user/%U"
ExecStart=$HOME_DIR/start-kiosk.sh
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
EOFSERVICE

print_status "Systemd user service created"

# Enable the service
systemctl --user daemon-reload
systemctl --user enable goldenmunch-kiosk.service
print_status "Systemd service enabled"

# Step 5: Create helper scripts
echo -e "\n${BLUE}Step 5: Creating helper scripts...${NC}"

# Stop kiosk script
cat > "$HOME_DIR/stop-kiosk.sh" << 'EOFSTOP'
#!/bin/bash
echo "Stopping GoldenMunch Kiosk..."
pkill -f chromium-browser
pkill -f "node.*server"
pkill -f "next-server.*3000"
pkill -f unclutter
echo "Kiosk stopped"
EOFSTOP

chmod +x "$HOME_DIR/stop-kiosk.sh"
print_status "Stop script created: $HOME_DIR/stop-kiosk.sh"

# Restart kiosk script
cat > "$HOME_DIR/restart-kiosk.sh" << EOFRESTART
#!/bin/bash
echo "Restarting GoldenMunch Kiosk..."
$HOME_DIR/stop-kiosk.sh
sleep 3
$HOME_DIR/start-kiosk.sh &
echo "Kiosk restarted"
EOFRESTART

chmod +x "$HOME_DIR/restart-kiosk.sh"
print_status "Restart script created: $HOME_DIR/restart-kiosk.sh"

# View logs script
cat > "$HOME_DIR/view-kiosk-logs.sh" << EOFLOGS
#!/bin/bash
echo "=== Kiosk Startup Log ==="
tail -n 50 $HOME_DIR/kiosk-startup.log
echo ""
echo "=== Server Output ==="
tail -n 30 $HOME_DIR/server-output.log
echo ""
echo "=== Frontend Output ==="
tail -n 30 $HOME_DIR/frontend-output.log
echo ""
echo "=== Chromium Output ==="
tail -n 20 $HOME_DIR/chromium-output.log
EOFLOGS

chmod +x "$HOME_DIR/view-kiosk-logs.sh"
print_status "Log viewer script created: $HOME_DIR/view-kiosk-logs.sh"

# Step 6: Check and install npm dependencies
echo -e "\n${BLUE}Step 6: Checking npm dependencies...${NC}"

# Check server dependencies
if [ -d "$PROJECT_DIR/server" ] && [ -f "$PROJECT_DIR/server/package.json" ]; then
    cd "$PROJECT_DIR/server"
    if [ ! -d "node_modules" ]; then
        print_info "Installing server dependencies..."
        npm install
        print_status "Server dependencies installed"
    else
        print_status "Server dependencies already installed"
    fi
else
    print_warning "Server directory not found or package.json missing"
fi

# Check frontend dependencies
if [ -d "$PROJECT_DIR/client/Kiosk_Web" ] && [ -f "$PROJECT_DIR/client/Kiosk_Web/package.json" ]; then
    cd "$PROJECT_DIR/client/Kiosk_Web"
    if [ ! -d "node_modules" ]; then
        print_info "Installing frontend dependencies..."
        npm install
        print_status "Frontend dependencies installed"
    else
        print_status "Frontend dependencies already installed"
    fi
else
    print_warning "Frontend directory not found or package.json missing"
fi

cd "$HOME_DIR"

# Step 7: Configure boot options info
echo -e "\n${BLUE}Step 7: Boot configuration information${NC}"

print_info "To complete setup, you need to enable auto-login:"
echo ""
echo -e "${YELLOW}Run this command:${NC}"
echo "    sudo raspi-config"
echo ""
echo "Then navigate to:"
echo "  1. System Options → Boot / Auto Login"
echo "  2. Select: Desktop Autologin"
echo "  3. Press OK and reboot"
echo ""

# Step 8: Summary
echo -e "\n${GREEN}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              Installation Complete! 🎉                 ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════╝${NC}"
echo ""

print_status "Setup completed successfully!"
echo ""
echo -e "${BLUE}Created files:${NC}"
echo "  • $HOME_DIR/start-kiosk.sh"
echo "  • $HOME_DIR/stop-kiosk.sh"
echo "  • $HOME_DIR/restart-kiosk.sh"
echo "  • $HOME_DIR/view-kiosk-logs.sh"
echo "  • $HOME_DIR/.config/labwc/autostart"
echo "  • $HOME_DIR/.config/systemd/user/goldenmunch-kiosk.service"
echo ""

echo -e "${BLUE}Quick Commands:${NC}"
echo "  • Test kiosk manually:    ./start-kiosk.sh"
echo "  • Stop kiosk:             ./stop-kiosk.sh"
echo "  • Restart kiosk:          ./restart-kiosk.sh"
echo "  • View logs:              ./view-kiosk-logs.sh"
echo "  • Check service status:   systemctl --user status goldenmunch-kiosk"
echo ""

echo -e "${YELLOW}Next Steps:${NC}"
echo "  1. Configure auto-login with: sudo raspi-config"
echo "  2. Test the kiosk: ./start-kiosk.sh"
echo "  3. If working, reboot to test autostart: sudo reboot"
echo ""

print_info "Log files will be created in your home directory:"
echo "  • ~/kiosk-startup.log"
echo "  • ~/server-output.log"
echo "  • ~/frontend-output.log"
echo "  • ~/chromium-output.log"
echo ""

print_warning "Important: Make sure to enable auto-login in raspi-config!"
echo ""

read -p "Would you like to test the kiosk now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    print_info "Starting kiosk in 3 seconds..."
    sleep 3
    $HOME_DIR/start-kiosk.sh &
    print_status "Kiosk started! Check if the browser opens."
    echo ""
    print_info "To stop it, run: ./stop-kiosk.sh"
fi

echo ""
print_status "Setup script finished!"
